=== torrentg/ccruncher/ccruncher/trunk/samples/creditcruncher-0.1.dtd
<!-- ============================================================== -->
<!--                DTD CREDITCRUNCHER VERSION 0.1                  -->
<!-- ============================================================== -->


<!-- .............................................................. -->
<!--                       common stuff                             -->
<!-- .............................................................. -->
<!ELEMENT property 
    EMPTY
>
<!ATTLIST property 
    name CDATA #REQUIRED
    value CDATA #REQUIRED
>

<!-- .............................................................. -->
<!--                        creditcruncher                          -->
<!-- .............................................................. -->
<!ELEMENT creditcruncher (
    (params, interests, ratings, mtransitions, sectors, 
     mcorrels, segmentations, aggregators, portfolio)
)>

<!-- .............................................................. -->
<!--                           params                               -->
<!-- .............................................................. -->
<!ELEMENT params (
    property+
)>

<!-- .............................................................. -->
<!--                          interests                             -->
<!-- .............................................................. -->
<!ELEMENT interests (
    interest+
)>

<!ELEMENT interest (
    rate+
)>
<!ATTLIST interest
    name ID #REQUIRED
    date CDATA #REQUIRED
>

<!ELEMENT rate
    EMPTY
>
<!ATTLIST rate 
    t CDATA #REQUIRED
    r CDATA #REQUIRED
>

<!-- .............................................................. -->
<!--                           ratings                              -->
<!-- .............................................................. -->
<!ELEMENT ratings (
    rating+
)>

<!ELEMENT rating
    EMPTY
>
<!ATTLIST rating 
    name ID #REQUIRED
    order CDATA #REQUIRED
    desc CDATA #REQUIRED
>

<!-- .............................................................. -->
<!--                         mtransition                            -->
<!-- .............................................................. -->
<!ELEMENT mtransitions (
    transition+
)>
<!ATTLIST mtransitions
    period CDATA #REQUIRED
    epsilon CDATA #REQUIRED
>

<!ELEMENT transition
    EMPTY
>
<!ATTLIST transition
    from IDREF #REQUIRED
    to IDREF #REQUIRED
    value CDATA #REQUIRED
>

<!-- .............................................................. -->
<!--                         sectors                                -->
<!-- .............................................................. -->
<!ELEMENT sectors (
    sector+
)>

<!ELEMENT sector
    EMPTY
>
<!ATTLIST sector
    name ID #REQUIRED
    order CDATA #REQUIRED
    desc CDATA #REQUIRED
>

<!-- .............................................................. -->
<!--                        correlations                            -->
<!-- .............................................................. -->
<!ELEMENT mcorrels (
    sigma+
)>
<!ATTLIST mcorrels
    epsilon CDATA #REQUIRED
>

<!ELEMENT sigma
    EMPTY
>
<!ATTLIST sigma
    sector1 IDREF #REQUIRED
    sector2 IDREF #REQUIRED
    value CDATA #REQUIRED
>

<!-- .............................................................. -->
<!--                         segmentations                          -->
<!-- .............................................................. -->
<!ELEMENT segmentations (
    segmentation*
)>

<!ELEMENT segmentation (
    segment*
)>
<!ATTLIST segmentation
    name CDATA #REQUIRED
    components (asset|client) #REQUIRED
>

<!ELEMENT segment
    EMPTY
>
<!ATTLIST segment 
    name CDATA #REQUIRED
>

<!-- .............................................................. -->
<!--                         aggregators                            -->
<!-- .............................................................. -->
<!ELEMENT aggregators (
    aggregator+
)>

<!ELEMENT aggregator
    EMPTY
>
<!ATTLIST aggregator
    name CDATA #REQUIRED
    segmentation CDATA #REQUIRED
    type (values|ratings) #REQUIRED
    full (true|false) #REQUIRED
>

<!-- .............................................................. -->
<!--                        portfolio                               -->
<!-- .............................................................. -->
<!ELEMENT portfolio (
    client+
)>

<!ELEMENT client (
    (belongs-to*, asset*)
)>
<!ATTLIST client
    id CDATA #REQUIRED
    name CDATA #REQUIRED
    rating IDREF #REQUIRED
    sector IDREF #REQUIRED
>

<!ELEMENT asset (
    (belongs-to*, property+)
)>
<!ATTLIST asset
    id CDATA #REQUIRED
    class (bond) #REQUIRED
>

<!ELEMENT belongs-to
    EMPTY
>
<!ATTLIST belongs-to 
    concept CDATA #REQUIRED
    segment CDATA #REQUIRED
>

=== torrentg/ccruncher/ccruncher/trunk/samples/sample50.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE creditcruncher SYSTEM "creditcruncher-0.1.dtd">

<creditcruncher>

  <!-- ============================================================== -->
  <!--                       PARAMETERS                               -->
  <!-- ============================================================== -->
  <params>
    <property name="time.begindate" value="18/02/2003"/>
    <property name="time.steps" value="12"/>
    <property name="time.steplength" value="2"/>
    <property name="stopcriteria.maxiterations" value="15000"/>
    <property name="stopcriteria.maxseconds" value="30000000"/>
    <property name="copula.type" value="normal"/>
    <property name="copula.seed" value="387650932"/>
    <property name="montecarlo.antithetic" value="false"/>
    <property name="portfolio.onlyActiveClients" value="true"/>
  </params>

  <!-- ============================================================== -->
  <!--                       INTERESTS                                -->
  <!-- ============================================================== -->
  <interests>
    <interest name="spot" date="18/11/2004">
      <rate t="0" r="0.0"/>
      <rate t="1" r="0.04"/>
      <rate t="2" r="0.041"/>
      <rate t="3" r="0.045"/>
      <rate t="6" r="0.0455"/>
      <rate t="12" r="0.048"/>
      <rate t="24" r="0.049"/>
      <rate t="60" r="0.05"/>
      <rate t="120" r="0.052"/>
    </interest>
  </interests>

  <!-- ============================================================== -->
  <!--                           RATINGS                              -->
  <!-- ============================================================== -->
  <ratings>
    <rating name="A" order="1" desc="excelent"/>
    <rating name="B" order="2" desc="good"/>
    <rating name="C" order="3" desc="medium"/>
    <rating name="D" order="4" desc="bad"/>
    <rating name="E" order="5" desc="default"/>
  </ratings>

  <!-- ============================================================== -->
  <!--                     TRANSITION MATRIX                          -->
  <!-- ============================================================== -->
  <mtransitions period="1" epsilon="1e-12">
    <transition from="A" to="A" value="0.80"/>
    <transition from="A" to="B" value="0.10"/>
    <transition from="A" to="C" value="0.07"/>
    <transition from="A" to="D" value="0.02"/>
    <transition from="A" to="E" value="0.01"/>
    <transition from="B" to="A" value="0.05"/>
    <transition from="B" to="B" value="0.75"/>
    <transition from="B" to="C" value="0.10"/>
    <transition from="B" to="D" value="0.07"/>
    <transition from="B" to="E" value="0.03"/>
    <transition from="C" to="A" value="0.03"/>
    <transition from="C" to="B" value="0.07"/>
    <transition from="C" to="C" value="0.70"/>
    <transition from="C" to="D" value="0.14"/>
    <transition from="C" to="E" value="0.06"/>
    <transition from="D" to="A" value="0.05"/>
    <transition from="D" to="B" value="0.05"/>
    <transition from="D" to="C" value="0.15"/>
    <transition from="D" to="D" value="0.60"/>
    <transition from="D" to="E" value="0.15"/>
    <transition from="E" to="A" value="0.00"/>
    <transition from="E" to="B" value="0.00"/>
    <transition from="E" to="C" value="0.00"/>
    <transition from="E" to="D" value="0.00"/>
    <transition from="E" to="E" value="1.00"/>
  </mtransitions>

  <!-- ============================================================== -->
  <!--                           SECTORS                              -->
  <!-- ============================================================== -->
  <sectors>
    <sector name="S1" order="1" desc="oil and gas"/>
    <sector name="S2" order="2" desc="other sectors"/>
  </sectors>

  <!-- ============================================================== -->
  <!--                        CORRELATIONS                            -->
  <!-- ============================================================== -->
  <mcorrels epsilon="1e-12">
    <sigma sector1="S1" sector2="S1" value="0.2"/>
    <sigma sector1="S1" sector2="S2" value="0.1"/> 
    <sigma sector1="S2" sector2="S2" value="0.25"/> 
  </mcorrels>

  <!-- ============================================================== -->
  <!--                       SEGMENTATIONS                            -->
  <!-- ============================================================== -->
  <segmentations>
    <segmentation name="portfolio" components="client"/>
    <segmentation name="client" components="client">
      <segment name="*"/>
    </segmentation>
    <segmentation name="asset" components="asset">
      <segment name="*"/>
    </segmentation>
    <segmentation name="sector" components="client">
      <segment name="S1"/>
      <segment name="S2"/>
    </segmentation>
    <segmentation name="size" components="client">
      <segment name="big"/>
      <segment name="medium"/>
    </segmentation>
    <segmentation name="product" components="asset">
      <segment name="bond"/>
    </segmentation>
    <segmentation name="office" components="asset">
      <segment name="0001"/>
      <segment name="0002"/>
      <segment name="0003"/>
      <segment name="0004"/>
    </segmentation>
  </segmentations>

  <!-- ============================================================== -->
  <!--                         AGGREGATORS                            -->
  <!-- ============================================================== -->
  <aggregators>
    <aggregator name="aggregator1" segmentation="portfolio" 
                type="values" full="true"/>
    <aggregator name="aggregator2" segmentation="portfolio" 
                type="ratings" full="false"/>
  </aggregators>
  
  <!-- ============================================================== -->
  <!--                         PORTFOLIO                              -->
  <!-- ============================================================== -->
  <portfolio>
    <client rating="A" sector="S1" name="Repsol" id="000001">
    </client>
    <client rating="B" sector="S2" name="ATT" id="000002">
      <belongs-to concept="sector" segment="S2"/>
      <belongs-to concept="size" segment="big"/>
      <!-- implicit: belongs-to concept="client" segment="cif2" -->
      <asset class="bond" id="op3"> 
        <belongs-to concept="office" segment="0003"/>
        <belongs-to concept="product" segment="bond"/>
        <!-- implicit: belongs-to concept="asset" segment="op3" -->
        <property name="issuedate" value="1/1/2000"/>
        <property name="term" value="120"/>
        <property name="nominal" value="1500.0"/>
        <property name="rate" value="0.07"/>
        <property name="ncoupons" value="5"/>
        <property name="adquisitiondate" value="1/1/2003"/>
        <property name="adquisitionprice" value="1500.0"/>
      </asset>
    </client>
    <client rating="A" sector="S1" name="pepe" id="000003">
      <asset class="bond" id="op4"> 
        <belongs-to concept="office" segment="0003"/>
        <belongs-to concept="product" segment="bond"/>
        <!-- implicit: belongs-to concept="asset" segment="op3" -->
        <property name="issuedate" value="1/1/2000"/>
        <property name="term" value="120"/>
        <property name="nominal" value="1500.0"/>
        <property name="rate" value="0.07"/>
        <property name="ncoupons" value="5"/>
        <property name="adquisitiondate" value="1/1/2003"/>
        <property name="adquisitionprice" value="1500.0"/>
      </asset>
    </client>    
<client rating='D' sector='S1' name='client0' id='0'>
  <asset class='bond' id='0-0'>
    <property name='issuedate' value='01/01/2000'/>
    <property name='term' value='120'/>
    <property name='nominal' value='1500'/>
    <property name='rate' value='0.07'/>
    <property name='ncoupons' value='120'/>
    <property name='adquisitiondate' value='1/1/2003'/>
    <property name='adquisitionprice' value='1500'/>
  </asset>
  <asset class='bond' id='0-1'>
    <property name='issuedate' value='01/01/2000'/>
    <property name='term' value='120'/>
    <property name='nominal' value='1500'/>
    <property name='rate' value='0.07'/>
    <property name='ncoupons' value='120'/>
    <property name='adquisitiondate' value='1/1/2003'/>
    <property name='adquisitionprice' value='1500'/>
  </asset>
  <asset class='bond' id='0-2'>
    <property name='issuedate' value='01/01/2000'/>
    <property name='term' value='120'/>
    <property name='nominal' value='1500'/>
    <property name='rate' value='0.07'/>
    <property name='ncoupons' value='120'/>
    <property name='adquisitiondate' value='1/1/2003'/>
    <property name='adquisitionprice' value='1500'/>
  </asset>
</client>
<client rating='B' sector='S2' name='client1' id='1'>
  <asset class='bond' id='1-0'>
    <property name='issuedate' value='01/01/2000'/>
    <property name='term' value='120'/>
    <property name='nominal' value='1500'/>
    <property name='rate' value='0.07'/>
    <property name='ncoupons' value='120'/>
    <property name='adquisitiondate' value='1/1/2003'/>
    <property name='adquisitionprice' value='1500'/>
  </asset>
  <asset class='bond' id='1-1'>
    <property name='issuedate' value='01/01/2000'/>
    <property name='term' value='120'/>
    <property name='nominal' value='1500'/>
    <property name='rate' value='0.07'/>
    <property name='ncoupons' value='120'/>
    <property name='adquisitiondate' value='1/1/2003'/>
    <property name='adquisitionprice' value='1500'/>
  </asset>
  <asset class='bond' id='1-2'>
    <property name='issuedate' value='01/01/2000'/>
    <property name='term' value='120'/>
    <property name='nominal' value='1500'/>
    <property name='rate' value='0.07'/>
    <property name='ncoupons' value='120'/>
    <property name='adquisitiondate' value='1/1/2003'/>
    <property name='adquisitionprice' value='1500'/>
  </asset>
</client>
<client rating='B' sector='S2' name='client2' id='2'>
  <asset class='bond' id='2-0'>
