=== torrentg/ccruncher/trunk/samples/ccruncher.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.generacio.com/ccruncher"
	targetNamespace="http://www.generacio.com/ccruncher"
	elementFormDefault="qualified">
	
	<!--
		  if you desire debug your xml add these lines to main tag:
		  xmlns="http://www.generacio.com/ccruncher"
		  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:schemaLocation="http://www.generacio.com/ccruncher ccruncher.xsd"
		
		  other way to do the same is:
		  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:noNamespaceSchemaLocation="ccruncher.xsd"
		
		  export CLASSPATH=$CLASSPATH:xercesImpl.jar:xml-apis.jar:xercesSamples.jar
		  java dom.Writer -v -s sample01.xml
		  java sax.Writer -v -s sample01.xml
	-->
	<xsd:annotation>
		<xsd:documentation xml:lang="en">
			Credit Cruncher Schema.
			Copyright 2007.
			Gerard Torrent Gironella.
		</xsd:documentation>
	</xsd:annotation>
	
	<xsd:element name="ccruncher" type="ccruncherType"/>
	
	<xsd:complexType name="ccruncherType">
		<xsd:sequence>
			<xsd:element name="params" minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="property" minOccurs="9" maxOccurs="9">
							<xsd:complexType>
								<xsd:attribute name="name" type="propertyType" use="required"/>
								<xsd:attribute name="value" type="xsd:string" use="required"/>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="interests" minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="interest" minOccurs="1" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="rate" minOccurs="1" maxOccurs="unbounded">
										<xsd:complexType>
											<xsd:attribute name="t" type="xsd:nonNegativeInteger" use="required"/>
											<xsd:attribute name="r" type="xsd:double" use="required"/>
										</xsd:complexType>
									</xsd:element>
								</xsd:sequence>
								<xsd:attribute name="name" type="xsd:string" use="required"/>
								<xsd:attribute name="date" type="myDate" use="required"/>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="ratings" minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="rating" minOccurs="2" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:attribute name="name" type="xsd:string" use="required"/>
								<xsd:attribute name="desc" type="xsd:string" use="required"/>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="mtransitions" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="transition" minOccurs="4" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:attribute name="from" type="xsd:string" use="required"/>
								<xsd:attribute name="to" type="xsd:string" use="required"/>
								<xsd:attribute name="value" type="xsd:double" use="required"/>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
					<xsd:attribute name="period" type="xsd:positiveInteger" use="required"/>
					<xsd:attribute name="epsilon" type="xsd:double" use="optional"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="survival" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="svalue" minOccurs="1" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:attribute name="rating" type="xsd:string" use="required"/>
								<xsd:attribute name="t" type="xsd:positiveInteger" use="required"/>
								<xsd:attribute name="value" type="xsd:double" use="required"/>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
					<xsd:attribute name="maxmonths" type="xsd:positiveInteger" use="required"/>
					<xsd:attribute name="epsilon" type="xsd:double" use="optional"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="sectors" minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="sector" minOccurs="1" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:attribute name="name" type="xsd:string" use="required"/>
								<xsd:attribute name="desc" type="xsd:string" use="required"/>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="mcorrels" minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="sigma" minOccurs="1" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:attribute name="sector1" type="xsd:string" use="required"/>
								<xsd:attribute name="sector2" type="xsd:string" use="required"/>
								<xsd:attribute name="value" type="xsd:double" use="required"/>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
					<xsd:attribute name="epsilon" type="xsd:double" use="optional"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="segmentations" minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="segmentation" minOccurs="1" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="segment" minOccurs="0" maxOccurs="unbounded">
										<xsd:complexType>
											<xsd:attribute name="name" type="xsd:string" use="required"/>
										</xsd:complexType>
									</xsd:element>
								</xsd:sequence>
								<xsd:attribute name="name" type="xsd:string" use="required"/>
								<xsd:attribute name="components" type="componentsType" use="required"/>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="portfolio" minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="borrower" minOccurs="1" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="belongs-to" minOccurs="0" maxOccurs="unbounded">
										<xsd:complexType>
											<xsd:attribute name="segmentation" type="xsd:string" use="required"/>
											<xsd:attribute name="segment" type="xsd:string" use="required"/>
										</xsd:complexType>
									</xsd:element>
									<xsd:element name="asset" minOccurs="1" maxOccurs="unbounded">
										<xsd:complexType>
											<xsd:sequence>
												<xsd:element name="belongs-to" minOccurs="0" maxOccurs="unbounded">
													<xsd:complexType>
														<xsd:attribute name="segmentation" type="xsd:string" use="required"/>
														<xsd:attribute name="segment" type="xsd:string" use="required"/>
													</xsd:complexType>
												</xsd:element>
												<xsd:element name="data" minOccurs="1" maxOccurs="1">
													<xsd:complexType>
														<xsd:sequence>
															<xsd:element name="values" minOccurs="1" maxOccurs="unbounded">
																<xsd:complexType>
																	<xsd:attribute name="at" type="myDate" use="required"/>
																	<xsd:attribute name="cashflow" type="xsd:double" use="required"/>
																	<xsd:attribute name="recovery" type="xsd:double" use="required"/>
																</xsd:complexType>
															</xsd:element>
														</xsd:sequence>
													</xsd:complexType>
												</xsd:element>
											</xsd:sequence>
											<xsd:attribute name="name" type="xsd:string" use="required"/>
											<xsd:attribute name="id" type="xsd:string" use="required"/>
											<xsd:attribute name="date" type="myDate" use="required"/>
										</xsd:complexType>
									</xsd:element>
								</xsd:sequence>
								<xsd:attribute name="name" type="xsd:string" use="required"/>
								<xsd:attribute name="id" type="xsd:string" use="required"/>
								<xsd:attribute name="rating" type="xsd:string" use="required"/>
								<xsd:attribute name="sector" type="xsd:string" use="required"/>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="propertyType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="time.begindate"/>
			<xsd:enumeration value="time.steps"/>
			<xsd:enumeration value="time.steplength"/>
			<xsd:enumeration value="stopcriteria.maxiterations"/>
			<xsd:enumeration value="stopcriteria.maxseconds"/>
			<xsd:enumeration value="copula.type"/>
			<xsd:enumeration value="copula.seed"/>
			<xsd:enumeration value="montecarlo.antithetic"/>
			<xsd:enumeration value="portfolio.onlyActiveBorrowers"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="componentsType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="asset"/>
			<xsd:enumeration value="borrower"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="myDate">
		<xsd:union memberTypes="xsd:date">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:pattern value="[0-3]?[0-9]/[0-1]?[0-9]/[1-2][0-9]{3}" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:union>
	</xsd:simpleType>
	
</xsd:schema>

=== torrentg/ccruncher/tags/ccruncher-1.7/samples/test01.xml
<?xml version="1.0" encoding="UTF-8"?>

<ccruncher
	xmlns="http://www.ccruncher.net"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ccruncher.net ccruncher.xsd">

  <title>test01</title>
  <description>
  <![CDATA[

Description:
-------------------------------
  1 obligor
  1 unique sector
  uncorrelated defaults (because only exist 1 obligor)
  2 ratings (dead and alive)
  transition values:
    P(alive->alive) = 0.9
    P(alive->dead)  = 0.1
    P(dead->alive)  = 0.0
    P(dead->dead)   = 1.0
  12 months
  The obligor has an unique asset with this profile:
    asset value at t=12 is 1 if obligor is alive and
    asset value at t=12 is 0 if obligor dead (default)

Expected Results:
-------------------------------
  This problem has an explicit solution. The asset loss
  at t=12 can be modeled as a Bernouilli(0.1). Then, the
  portfolio loss at t=12 can be modeled as Z~Bernouilli(0.1)
    P(Z=0) = 0.9
    P(Z=1) = 0.1

How to check results?
-------------------------------
  > #loading script
  > source("bin/ccreport.R")
  > #reading data
  > x <- ccruncher.read("data/portfolio.csv")
  > x <- x[,1]
  > #observed frequencies (number of 0's and 1's)
  > obs <- tabulate(x+1, 2)
  > #theoretical probabilities
  > prob <- c(0.9, 0.1)
  > #chi square test (if p-value > 0.05 means that is true)
  > cst <- chisq.test(obs, p=prob)
  > #if p-value > 0.05 than distribution is correct
  > cst$p.value

  ]]>
  </description>

  <!-- ============================================================== -->
  <!--                       PARAMETERS                               -->
  <!-- ============================================================== -->
  <parameters>
    <property name="time.0" value="01/01/2005"/>
    <property name="time.T" value="01/01/2006"/>
    <property name="stopcriteria.maxiterations" value="20000"/>
    <property name="stopcriteria.maxseconds" value="30000000"/>
    <property name="copula.type" value="gaussian"/>
    <property name="copula.seed" value="0"/>
    <property name="montecarlo.antithetic" value="false"/>
    <property name="portfolio.onlyActiveObligors" value="true"/>
  </parameters>

  <!-- ============================================================== -->
  <!--                       INTEREST                                 -->
  <!-- ============================================================== -->
  <interest type="compound">
    <rate t="0" r="0%"/>
    <rate t="1" r="0%"/>
    <rate t="2" r="0%"/>
    <rate t="3" r="0%"/>
    <rate t="6" r="0%"/>
    <rate t="12" r="0%"/>
    <rate t="24" r="0%"/>
    <rate t="60" r="0%"/>
    <rate t="120" r="0%"/>
  </interest>

  <!-- ============================================================== -->
  <!--                           RATINGS                              -->
  <!-- ============================================================== -->
  <ratings>
    <rating name="A" description="alive"/>
    <rating name="E" description="death"/>
  </ratings>

  <!-- ============================================================== -->
  <!--                     TRANSITION MATRIX                          -->
  <!-- ============================================================== -->
  <mtransitions period="12">
    <transition from="A" to="A" value="90%"/>
    <transition from="A" to="E" value="10%"/>
    <transition from="E" to="A" value="0%"/>
    <transition from="E" to="E" value="100%"/>
  </mtransitions>

  <!-- ============================================================== -->
  <!--                           SECTORS                              -->
  <!-- ============================================================== -->
  <sectors>
    <sector name="S1" description="unique sector"/>
  </sectors>

  <!-- ============================================================== -->
  <!--                        CORRELATIONS                            -->
  <!-- ============================================================== -->
  <mcorrels>
    <sigma sector1="S1" sector2="S1" value="0%"/>
  </mcorrels>

  <!-- ============================================================== -->
  <!--                       SEGMENTATIONS                            -->
  <!-- ============================================================== -->
  <segmentations>
    <segmentation name="portfolio" components="asset"/>
    <segmentation name="sectors" components="obligor">
      <segment name="S1"/>
    </segmentation>
  </segmentations>

  <!-- ============================================================== -->
  <!--                         PORTFOLIO                              -->
  <!-- ============================================================== -->
  <portfolio>
    <obligor rating="A" sector="S1" name="001" id="001">
      <belongs-to segmentation="sectors" segment="S1"/>
      <asset name="generic" id="op1" date="01/01/2005">
        <data>
          <values at="01/01/2007" exposure="1.0" recovery="0%" />
        </data>
      </asset>
    </obligor>
  </portfolio>

</ccruncher>
